# Generated by Django 4.0.2 on 2022-02-18 09:58

import django.core.validators
from django.db import migrations, models
import expences_tracker.expenses_tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0002_expense_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='budget',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=15, validators=[expences_tracker.expenses_tracker.validators.only_letters_validator, django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=15, validators=[expences_tracker.expenses_tracker.validators.only_letters_validator, django.core.validators.MinValueValidator(2)]),
        ),
    ]
