# Generated by Django 4.0.2 on 2022-02-18 13:35

from django.db import migrations, models
import expences_tracker.expenses_tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0003_alter_profile_budget_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=15, validators=[expences_tracker.expenses_tracker.validators.only_letters_validator, expences_tracker.expenses_tracker.validators.min_length_name_validator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=15, validators=[expences_tracker.expenses_tracker.validators.only_letters_validator, expences_tracker.expenses_tracker.validators.min_length_name_validator]),
        ),
    ]
