# Generated by Django 4.0.2 on 2022-02-20 14:59

from django.db import migrations, models
import expences_tracker.expenses_tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker', '0004_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[expences_tracker.expenses_tracker.models.MaxFileSizeInMBValidator(5)]),
        ),
    ]
